# Generated by Django 5.2.1 on 2025-06-07 03:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note_schedule_delete_at_note_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
