# Generated by Django 5.2.1 on 2025-06-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_first_name_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='notes',
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(through='api.NoteTag', to='api.tag'),
        ),
    ]
