# Generated by Django 5.2.1 on 2025-06-07 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_tag_notes_note_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='tags',
        ),
        migrations.AddField(
            model_name='usernote',
            name='tags',
            field=models.ManyToManyField(through='api.NoteTag', to='api.tag'),
        ),
        migrations.AlterField(
            model_name='notetag',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usernote'),
        ),
    ]
