# Generated by Django 5.1.2 on 2024-11-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0005_remove_user_roles_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='note_images/'),
        ),
        migrations.AddField(
            model_name='note',
            name='inRecycleBin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='isFavorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='isPinned',
            field=models.BooleanField(default=False),
        ),
    ]
