# Generated by Django 5.1.2 on 2024-11-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0006_note_image_note_inrecyclebin_note_isfavorite_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='inRecycleBin',
            new_name='in_recycleBin',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='isFavorite',
            new_name='is_favorite',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='isPinned',
            new_name='is_pinned',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
