# Generated by Django 5.2.1 on 2025-06-24 14:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_note_tags_usernote_tags_alter_notetag_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notebooknote',
            old_name='note_book',
            new_name='notebook',
        ),
        migrations.RenameField(
            model_name='usernotebook',
            old_name='note_book',
            new_name='notebook',
        ),
        migrations.AlterUniqueTogether(
            name='notebooknote',
            unique_together={('note', 'notebook')},
        ),
        migrations.AlterUniqueTogether(
            name='usernotebook',
            unique_together={('user', 'notebook')},
        ),
        migrations.AlterField(
            model_name='notebook',
            name='notes',
            field=models.ManyToManyField(through='api.NotebookNote', to='api.note'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='users',
            field=models.ManyToManyField(through='api.UserNotebook', through_fields=('notebook', 'user'), to=settings.AUTH_USER_MODEL),
        ),
    ]
