# Generated by Django 5.1.2 on 2024-11-25 21:22

import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0007_rename_inrecyclebin_note_in_recyclebin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
