# Generated by Django 5.2.1 on 2025-07-12 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_note_book_notebooknote_notebook_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernote',
            old_name='favorited_at',
            new_name='favorite_at',
        ),
        migrations.RenameField(
            model_name='usernote',
            old_name='is_favorited',
            new_name='is_favorite',
        ),
        migrations.RenameField(
            model_name='usernotebook',
            old_name='is_favorited',
            new_name='is_favorite',
        ),
    ]
