# Generated by Django 5.2.1 on 2025-07-18 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_favorited_at_usernote_favorite_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernote',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='usernotebook',
            name='is_archived',
        ),
    ]
