# Generated by Django 5.1.2 on 2024-11-25 22:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0008_alter_note_content_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
