# Generated by Django 5.1.2 on 2024-12-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0009_alter_note_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='note',
            name='last_updated',
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(),
        ),
    ]
