# Generated by Django 5.1.2 on 2024-12-10 20:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0010_remove_note_date_created_remove_note_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='image',
        ),
    ]
