# Generated by Django 5.1.2 on 2025-01-13 01:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0011_remove_note_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
