# Generated by Django 5.1.5 on 2025-01-18 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_in_recyclebin_note_is_trashed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='is_archive',
            new_name='is_archived',
        ),
    ]
