# Generated by Django 5.1.5 on 2025-01-18 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_is_archive_note_is_archived'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='is_favorite',
            new_name='is_favorited',
        ),
    ]
