# Generated by Django 5.1.5 on 2025-03-04 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_note_is_archived_remove_note_is_favorited_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Note',
            new_name='UserNote',
        ),
    ]
