# Generated by Django 5.2.1 on 2025-05-29 21:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_note_created_at_note_updated_at_tag_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
