# Generated by Django 5.2.1 on 2025-05-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_user_profile_picture_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.TextField(blank=True, null=True),
        ),
    ]
