# Generated by Django 5.1.2 on 2024-10-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_remove_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True,
                                      help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.',
                                      verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False,
                                      help_text='Designates whether the user can log into this admin site.',
                                      verbose_name='staff status'),
        ),
    ]
