# Generated by Django 5.1.2 on 2024-10-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_alter_user_is_active_alter_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('A', 'Admin'), ('CC', 'Company Clerk'), ('C', 'Clerk')], default='A',
                                   max_length=2),
        ),
    ]
