# Generated by Django 5.1.5 on 2025-01-16 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_note_is_archive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='in_recycleBin',
            new_name='is_trashed',
        ),
    ]
