# Generated by Django 5.1.5 on 2025-01-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_note_user_remove_tag_user_note_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='notes', to='api.tag'),
        ),
    ]
