# Generated by Django 5.1.5 on 2025-01-27 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_note_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='color',
        ),
    ]
