# Generated by Django 5.1.5 on 2025-03-04 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_tag_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='note',
            name='is_favorited',
        ),
        migrations.RemoveField(
            model_name='note',
            name='is_pinned',
        ),
        migrations.RemoveField(
            model_name='note',
            name='is_trashed',
        ),
        migrations.RemoveField(
            model_name='note',
            name='tags',
        ),
        migrations.CreateModel(
            name='User_Note',
            fields=[
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('EDITOR', 'Editor'), ('MEMBER', 'Member')], default='OWNER', max_length=20)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_favorited', models.BooleanField(default=False)),
                ('is_trashed', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.note')),
                ('tags', models.ManyToManyField(blank=True, related_name='User_tags', to='api.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
