apiVersion: apps/v1
kind: Deployment
metadata:
  name: Notetify-frontend
spec:
  selector:
    matchLabels:
      app: Notetify-frontend
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: Notetify-frontend
    spec:
      containers:
      - name: notetify-frontend
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "200Mi"  # Maximum memory allowed
            cpu: "200m"       # Maximum CPU allowed (200 milliCPU)
          requests:
            memory: "150Mi"  # Initial memory request
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /                # The path to check for the liveness probe
            port: 80               # The port to check on
          initialDelaySeconds: 15  # Wait this many seconds before starting the probe
          periodSeconds: 10        # Check the probe every 10 seconds
        readinessProbe:
          httpGet:
            path: /                # The path to check for the readiness probe
            port: 80               # The port to check on
          initialDelaySeconds: 5   # Wait this many seconds before starting the probe
          periodSeconds: 5         # Check the probe every 5 seconds


---

